import { Product, Review, Brand, Category } from "@/types";

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Shop by Brand", image: "https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&q=80&w=800", count: 120 },
  { id: "cat-2", name: "Shop by Origin", image: "https://images.unsplash.com/photo-1623156372580-0d321f478952?auto=format&fit=crop&q=80&w=800", count: 85 },
  { id: "cat-3", name: "Gourmet Baking", image: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&q=80&w=800", count: 45 },
  { id: "cat-4", name: "Chocolate Bars", image: "https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?auto=format&fit=crop&q=80&w=800", count: 200 },
];

export const mockBrands: Brand[] = [
  { id: "b1", name: "Valrhona", logo: "/logos/valrhona.png", rating: 4.9, reviewCount: 320, category: "Premium French Chocolate" },
  { id: "b2", name: "Callebaut", logo: "/logos/callebaut.png", rating: 4.8, reviewCount: 890, category: "Belgian Couverture" },
  { id: "b3", name: "KESSHŌ", logo: "/logos/kessho.png", rating: 5.0, reviewCount: 42, category: "Artisan Craft Chocolate" },
  { id: "b4", name: "Crow & Moss", logo: "/logos/crowmoss.png", rating: 4.9, reviewCount: 28, category: "Micro-batch Chocolate" },
];

export const mockProducts: Product[] = [
  {
    id: "choc-1",
    name: "KESSHŌ - 70% Dark Chocolate with Nibs",
    description: "Award-winning craft chocolate from Texas. This 70% dark chocolate bar is topped with crunchy roasted cocoa nibs for an intense chocolate experience.",
    price: 12.00,
    images: ["https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&q=80&w=800"],
    vendor: {
      id: "v-kessho",
      name: "KESSHŌ Chocolate",
      rating: 5.0,
      reviewCount: 42,
      location: "Austin, TX",
    },
    category: "Shop by Brand",
    tags: ["dark chocolate", "craft chocolate", "award-winning"],
    dimensions: { length: 6, width: 3, height: 0.5, weight: 0.15 },
    shippingOptions: [{ id: "s1", name: "Standard Shipping", price: 8.00, estimatedDays: 3 }],
    inStock: true,
    minOrderQuantity: 12,
    sampleAvailable: true,
    isBestseller: true,
    showWholesalePrice: true,
  },
  {
    id: "choc-2",
    name: "Madagascar Bejofo Estate 70% Dark",
    description: "Grown in the Sambirano Valley of Madagascar, this single-estate chocolate is known for its bright, fruity notes of citrus and red berries.",
    price: 9.50,
    images: ["https://images.unsplash.com/photo-1623156372580-0d321f478952?auto=format&fit=crop&q=80&w=800"],
    vendor: {
      id: "v-worldwide",
      name: "Worldwide Chocolate",
      rating: 4.8,
      reviewCount: 156,
      location: "Global Heritage",
    },
    category: "Shop by Origin",
    tags: ["Madagascar", "single-origin", "fruity"],
    dimensions: { length: 6, width: 3, height: 0.5, weight: 0.15 },
    shippingOptions: [{ id: "s1", name: "Standard Shipping", price: 8.00, estimatedDays: 3 }],
    inStock: true,
    minOrderQuantity: 24,
    sampleAvailable: true,
    showWholesalePrice: true,
  },
  {
    id: "choc-3",
    name: "Valrhona Poudre de Cacao - Dutch Processed",
    description: "Professional grade, Dutch-processed cocoa powder from Valrhona. Exceptional chocolate intensity and deep mahogany color.",
    price: 45.00,
    images: ["https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&q=80&w=800"],
    vendor: {
      id: "v-valrhona",
      name: "Valrhona",
      rating: 4.9,
      reviewCount: 320,
      location: "Tain-l'Hermitage, France",
    },
    category: "Gourmet Baking",
    tags: ["baking", "cocoa powder", "professional"],
    dimensions: { length: 5, width: 5, height: 7, weight: 2.2 },
    shippingOptions: [{ id: "s1", name: "Standard Shipping", price: 12.00, estimatedDays: 5 }],
    inStock: true,
    minOrderQuantity: 6,
    isBestseller: true,
    sampleAvailable: true,
    showWholesalePrice: true,
  },
  {
    id: "choc-4",
    name: "Callebaut 811 54.5% Dark Couverture Callets",
    description: "The iconic all-purpose dark chocolate used by chefs worldwide. Balanced cocoa flavor with hints of vanilla.",
    price: 38.00,
    images: ["https://images.unsplash.com/photo-1623860000109-770ce89f3a69?auto=format&fit=crop&q=80&w=800"],
    vendor: {
      id: "v-callebaut",
      name: "Callebaut",
      rating: 4.7,
      reviewCount: 890,
      location: "Wieze, Belgium",
    },
    category: "Shop by Brand",
    tags: ["baking", "couverture", "bulk"],
    dimensions: { length: 12, width: 8, height: 4, weight: 5.5 },
    shippingOptions: [{ id: "s1", name: "FedEx Ground", price: 15.00, estimatedDays: 4 }],
    inStock: true,
    minOrderQuantity: 2,
    isBestseller: true,
    sampleAvailable: true,
    showWholesalePrice: true,
  },
  {
    id: "choc-5",
    name: "Ecuador Arriba Nacional 85% Dark",
    description: "Intense floral and earthy notes from the rare Arriba Nacional cocoa beans of Ecuador. A true connoisseur's choice.",
    price: 11.00,
    images: ["https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?auto=format&fit=crop&q=80&w=800"],
    vendor: {
      id: "v-worldwide",
      name: "Worldwide Chocolate",
      rating: 4.8,
      reviewCount: 156,
      location: "Quito, Ecuador",
    },
    category: "Shop by Origin",
    tags: ["Ecuador", "high-percentage", "floral"],
    dimensions: { length: 6, width: 3, height: 0.5, weight: 0.15 },
    shippingOptions: [{ id: "s1", name: "Standard Shipping", price: 8.00, estimatedDays: 3 }],
    inStock: true,
    minOrderQuantity: 12,
    isNew: true,
    sampleAvailable: true,
    showWholesalePrice: true,
  },
  {
    id: "choc-6",
    name: "Crow & Moss Honduras Baking Batons 70%",
    description: "Perfect for pain au chocolat, these single-origin baking batons offer distinct honeycomb and toasted nut notes.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&q=80&w=800"],
    vendor: {
      id: "v-crowmoss",
      name: "Crow & Moss",
      rating: 4.9,
      reviewCount: 28,
      location: "Petoskey, MI",
    },
    category: "Gourmet Baking",
    tags: ["baking sticks", "pastry", "Honduras"],
    dimensions: { length: 10, width: 4, height: 2, weight: 2.0 },
    shippingOptions: [{ id: "s1", name: "Priority Mail", price: 10.00, estimatedDays: 2 }],
    inStock: true,
    minOrderQuantity: 12,
    isBestseller: true,
    sampleAvailable: true,
    showWholesalePrice: true,
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    productId: "choc-1",
    userId: "u1",
    userName: "Alice Johnson",
    rating: 5,
    comment: "The best dark chocolate I've ever had! The nibs add such a great crunch.",
    date: new Date("2024-02-15"),
    verifiedPurchase: true,
    helpfulCount: 12,
  },
  {
    id: "r2",
    productId: "choc-3",
    userId: "u2",
    userName: "Bob Smith",
    rating: 5,
    comment: "Valrhona cocoa powder is and always will be the best for baking.",
    date: new Date("2024-02-10"),
    verifiedPurchase: true,
    helpfulCount: 8,
  },
];

export const getProductById = (id: string) => {
  return mockProducts.find((p) => p.id === id);
};

export const getVendors = () => {
  const vendors = mockProducts.map((p) => p.vendor.name);
  return Array.from(new Set(vendors));
};
